name: better_player_example
description: Better Player example usage app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.5
  collection: ^1.19.0

  better_player:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true